spring.application.name=dvrs
jwt.secret=t3_3St0Y#M1r4Nd0$Y4%n0_H4y@M4t3r14_3S*uN_v1C10~3s_uN_h4B1t0.

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/miras_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Redis Configuration (Nuestra App en BD 1, separada de WVP)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=1